### ISSUE TITLE
Workflow "Create VS": server_cloud is not populated.

### ISSUE THREAD

**Issue by bmarkussen** [avinetworks/avi-vrealize-orchestrator-plugin#136]
### Describe the bug

Issue linked to https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/issues/126

vRA/vRO 8.11 single node:
Avi 22.1.3
vRO Plugin 22.1.3
AVI Configured Cloud: VMware vCenter/vSphere ESX

Error 1:
Executing workflow "Attach Avi Controller" runs without errors, but configured Virtual Services are not shown in inventory:
![image](https://user-images.githubusercontent.com/64780343/220870048-f23b0297-9a33-4d4b-90b8-71617360f381.png)

Error 2:
Executing workflow "Create VS" the server_cloud dropdown is not populated:
![image](https://user-images.githubusercontent.com/64780343/220870326-3908cce5-d155-4f23-9782-fb1b8c9c6e7a.png)

### Reproduction steps

1.Upgrade Avi vRO Plugin to latest.
...

### Expected behavior

server_cloud shown in dropdown

**Comment by mkhachane** [comment]
Can we get the logs bundle for the same?

**Comment by bmarkussen** [comment]
Hi @mkhachane,
Thank you for looking into this issue.
Yes, log bundle is uploaded to https://ftpsite.vmware.com/avi_vro_plugin_issue_136

/Brian

**Comment by mkhachane** [comment]
Hi @bmarkussen 
We have fixed the issue and release the vRO plugin 22.1.3.post2. You can find release dar file on GitHub releases.
