### ISSUE TITLE
Release Notes describing fixes and known issues

### ISSUE THREAD

**Issue by bmarkussen** [avinetworks/avi-vrealize-orchestrator-plugin#137]
### Is your feature request related to a problem? Please describe.

Please provide release notes for each new release.

### Describe the solution you'd like

Please provide release notes for each new release.

Containing:
- Fixes
- Known Issues
- Supported version etc: vRO/vRA/AVI

**Comment by bmarkussen** [comment]
Is there any documentation for what has been fixed/changed in the newly released 22.1.3.post1? https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/releases/tag/22.1.3.post1

Has these errors been fixed?
1.	SR23411450603
2.	https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/issues/136

**Comment by linyong-lee** [comment]
I Installed avi plug-in 21.1.6. in vRA8.6.2 Orchestrator.
But, I couldn't find avi workflows.

**Comment by vbarry** [comment]
I Installed avi plug-in 22.1.3.3. in vRA8.6.2 Orchestrator and I also couldn't find AVI workflows.
Reported to VMware Support in case 23432507805.

Re: Compatibility
Plug-in is missing from Interoperability matrix.
Documentation for plug-in is missing from https://github.com/vmware/vrealize-orchestrator-plugin-for-alb.

**Comment by vbarry** [comment]
I installed the following exact version from Marketplace instead and the Workflows appeared
https://marketplace.cloud.vmware.com/services/details/vmware-nsx-advanced-load-balancer-by-avi-networks-plug-in-for-vrealize-orchestrator-2112-11-11?slug=true

**Comment by vbarry** [comment]
> I Installed avi plug-in 21.1.6. in vRA8.6.2 Orchestrator. But, I couldn't find avi workflows.

Please see above

**Comment by jbourrigaud** [comment]
hello, thanks for this plugin but i have difficulties to use it with the very first workflow concerning "attach controller"
wich parameter should be put for "version" with latest version of your plugin ? "22.1.3.3.RELEASE.50" or only part of it. 
The attachment seems to work (an item is added into inventory part) but no VS or children objects are visible. we have checked connectivity between vro and alb and it is ok.

please suggest.

**Comment by jbourrigaud** [comment]
> hello, thanks for this plugin but i have difficulties to use it with the very first workflow concerning "attach controller" wich parameter should be put for "version" with latest version of your plugin ? "22.1.3.3.RELEASE.50" or only part of it. The attachment seems to work (an item is added into inventory part) but no VS or children objects are visible. we have checked connectivity between vro and alb and it is ok.
> 
> please suggest.

The version of the plugin should be sync with version of the web portal otherwise it won't work correctly. Attachment of the controller will be completed with success but the Inventory will not disply any items.

**Comment by mkhachane** [comment]
> hello, thanks for this plugin but i have difficulties to use it with the very first workflow concerning "attach controller" wich parameter should be put for "version" with latest version of your plugin ? "22.1.3.3.RELEASE.50" or only part of it. The attachment seems to work (an item is added into inventory part) but no VS or children objects are visible. we have checked connectivity between vro and alb and it is ok.
> 
> please suggest.

Hello, Yes the value for "version" parameter should be "22.1.3"(first three bits) which is part of the plugin version "22.1.3.3.RELEASE.50".

**Comment by mkhachane** [comment]
> > hello, thanks for this plugin but i have difficulties to use it with the very first workflow concerning "attach controller" wich parameter should be put for "version" with latest version of your plugin ? "22.1.3.3.RELEASE.50" or only part of it. The attachment seems to work (an item is added into inventory part) but no VS or children objects are visible. we have checked connectivity between vro and alb and it is ok.
> > please suggest.
> 
> The version of the plugin should be sync with version of the web portal otherwise it won't work correctly. Attachment of the controller will be completed with success but the Inventory will not disply any items.

Yes. We will release note the controller version for which the vRO plugin is released.

**Comment by BrianMarkussen** [comment]
I see that in 22.1.4 release notes has been added.

You can close this issue. @mkhachane 

Thank you.
