### ISSUE TITLE
Create Pool Error: {"error": "tier1_lr not configured"}

### ISSUE THREAD

**Issue by ej-github** [avinetworks/avi-vrealize-orchestrator-plugin#157]
### Describe the bug

This happens in plugin 22.1.3 and I also tried 22.1.3.post3
NSX ALB version 22.1.2.
3 node VRA 8.8.1 cluster with embedded VRO.

When running the **Create Pool** workflow it generates the following error:
```
(com.vmware.avi/finishVroWorkflow) Error in (Dynamic Script Module name : finishVroWorkflow#4) 
{"error": "tier1_lr not configured"}:: Inside Rollback ::null
::null
```
There is no input in the workflow to select an existing Tier 1 Logical Router.

### Reproduction steps

1. Run **Create Pool** workflow
2. Fill out the form
3. Submit

### Expected behavior

A pool should get created.

**Comment by haahaakon** [comment]
I am experiencing the same issue. Not only with Create Pool, but multiple other workflows.

There is a tier1_lr field, but it's hidden since the "visibility" option in the Input Form is conditional and based on a External source.

**Comment by jbourrigaud** [comment]
hello teams,

i have installed a fresh new version of the plugin and when i go to schema for the workflow 'Create a Pool' i receive the following message. i am with plugin version 22.1.3.3.RELEASE 50 (last official). I dont uderstand if i have to update /promote the workflows on issue or if this is a package issue / plugin installation issue.
- please suggest as the plugin seems to be very cool to use.
![image](https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/assets/134519658/4b0474a0-b5d4-4666-a65f-da46f0aa7c77)

below is workflow version 
![image](https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/assets/134519658/a2728620-50fb-4817-b838-9acfc9d6ec1a)
and the action version
![image](https://github.com/vmware/vrealize-orchestrator-plugin-for-alb/assets/134519658/01bf4cdf-a2ef-47ce-8e3c-c93ac03ab818)

**Comment by mkhachane** [comment]
> hello teams,
> 
> i have installed a fresh new version of the plugin and when i go to schema for the workflow 'Create a Pool' i receive the following message. i am with plugin version 22.1.3.3.RELEASE 50 (last official). I dont uderstand if i have to update /promote the workflows on issue or if this is a package issue / plugin installation issue.
> 
> * please suggest as the plugin seems to be very cool to use.
>   ![image](https://user-images.githubusercontent.com/134519658/245415965-4b0474a0-b5d4-4666-a65f-da46f0aa7c77.png)
> 
> below is workflow version ![image](https://user-images.githubusercontent.com/134519658/245417034-a2728620-50fb-4817-b838-9acfc9d6ec1a.png) and the action version ![image](https://user-images.githubusercontent.com/134519658/245417365-01bf4cdf-a2ef-47ce-8e3c-c93ac03ab818.png)

Hello, @jbourrigaud 
     You can update the workflows parameters and If you promote the params then you need to add the values for params.

**Comment by mkhachane** [comment]
> I am experiencing the same issue. Not only with Create Pool, but multiple other workflows.
> 
> There is a tier1_lr field, but it's hidden since the "visibility" option in the Input Form is conditional and based on a External source.

Hi,  @ej-github , @fluffyhake 
These workflows are not designed for all possible scenarios. These are just examples to create their custom workflows. This above error log shows validation error for tier1_lr information missing in Pool config. 
To fix this workflow needs to be updated to support NSX-T cloud. If we support that it will fail for other clouds so we wont add cloud specific info in this workflow which we release with the Plugin. 

Here, you can update/add new parameter for tier1_lr in the workflow and mapped it to the action.

**Comment by jbourrigaud** [comment]
> > I am experiencing the same issue. Not only with Create Pool, but multiple other workflows.
> > There is a tier1_lr field, but it's hidden since the "visibility" option in the Input Form is conditional and based on a External source.
> 
> Hi, @ej-github , @fluffyhake These workflows are not designed for all possible scenarios. These are just examples to create their custom workflows. This above error log shows validation error for tier1_lr information missing in Pool config. To fix this workflow needs to be updated to support NSX-T cloud. If we support that it will fail for other clouds so we wont add cloud specific info in this workflow which we release with the Plugin.
> 
> Here, you can update/add new parameter for tier1_lr in the workflow and mapped it to the action.

very interesting as comment.
should we then consider workflows available only as kind of template to be used and customize them when it is not working as our needs ?
i was expected to use workflows and actions as it is without any change like for plugin v21.1.3 which was working fine. with 22.1.3 it is a little more complex.

**Comment by mkhachane** [comment]
> > > I am experiencing the same issue. Not only with Create Pool, but multiple other workflows.
> > > There is a tier1_lr field, but it's hidden since the "visibility" option in the Input Form is conditional and based on a External source.
> > 
> > 
> > Hi, @ej-github , @fluffyhake These workflows are not designed for all possible scenarios. These are just examples to create their custom workflows. This above error log shows validation error for tier1_lr information missing in Pool config. To fix this workflow needs to be updated to support NSX-T cloud. If we support that it will fail for other clouds so we wont add cloud specific info in this workflow which we release with the Plugin.
> > Here, you can update/add new parameter for tier1_lr in the workflow and mapped it to the action.
> 
> very interesting as comment. should we then consider workflows available only as kind of template to be used and customize them when it is not working as our needs ? i was expected to use workflows and actions as it is without any change like for plugin v21.1.3 which was working fine. with 22.1.3 it is a little more complex.

Yes, can be considered as a template, which can be customised as per the use case.
We have provided workflows in v21.1.3 version with some basic config. Workflows and actions in v22.1.3 remains same, but with support for configuring additional parameters .
