### ISSUE TITLE
Support multiple tenants for the same AVI controller

### ISSUE THREAD

**Issue by srlynch1** [avinetworks/avi-vrealize-orchestrator-plugin#44]
As a consumer of AVI SaaS, I have use tenanted controllers, 2 or more tenants.

As AVI SaaS inventory connection is connected using the FQDN I can only have one connection per tenant, adding a new tenant with the same controller results in update rather than an additional tenant in the vRO inventory

This could be handled by allowing the user to supply a controller inventory name additional to fqdn or by appending a tenant to the inventory name to ensure uniqueness.

**Comment by chaitanyaavi** [comment]
Fixed in https://github.com/avinetworks/avi-vrealize-orchestrator-plugin/pull/95
