### ISSUE TITLE
[Feature Request] - Add support to createIPAMVsVIPObj for public cloud auto allocation

### ISSUE THREAD

**Issue by srlynch1** [avinetworks/avi-vrealize-orchestrator-plugin#47]
createIPAMVsVIPObj ideally should support AWS/Azure, though is currently written for vSphere Cloud infrastructure. The current implementation has dependencies on network lookup that are not applicable to public cloud, so this action doesn't work as is for AWS/Azure

Requirement is to have an action for auto allocation in AWS/Azure, if the action createIPAMVsVIPObj  is targeted at vSphere only ideally name is as such.

**Comment by chaitanyaavi** [comment]
Fixed in https://github.com/avinetworks/avi-vrealize-orchestrator-plugin/pull/98
