### ISSUE TITLE
Package installation fails

### ISSUE THREAD

**Issue by mpoore** [avinetworks/avi-vrealize-orchestrator-plugin#92]
The library workflow package fails to install with the plugin. Although the plugin itself is installed, the majority of the workflows and actions are not present afterwards. The following exception can be seen in the logs from vRO:

Unable to perform plug-in installation 'Avi', reason : (plug-in - Avi) Unable to install package 'packages/o11nplugin-vro-package-21.1.2.RELEASE.package' , reason : java.lang.IllegalArgumentException: The workflow name contains invalid characters (\, /).Name: null. ID: null

Unpacking the .dar file and attempting a manual package installation also fails, with vRO reporting "Failed to parse the provided package. It is invalid or corrupted."

**Comment by chaitanyaavi** [comment]
We are not able to reproduce this if still persist on your side can you please check with latest release https://github.com/avinetworks/avi-vrealize-orchestrator-plugin/releases/tag/tag-21.1.2.1.RELEASE

**Comment by mpoore** [comment]
Thank you, Chaitanya. The latest version worked without any problems. Closing this issue.
