### ISSUE TITLE
Rollback exception hides root cause exception

### ISSUE THREAD

**Issue by prydin** [avinetworks/avi-vrealize-orchestrator-plugin#99]
When calling the "executeWorkflow" function from vRO, the original exception is lost if the rollback fails. This makes troubleshooting extremely difficult. 

Suggestion: Wrap the original exception in the exception from the rollback or drop the rollback exception altogether, since it's probably just a cascading effect from the original exception. 

See this line in the source code: 
https://github.com/avinetworks/avi-vrealize-orchestrator-plugin/blob/cffe66241d57f775f4263050dfca4ae911ef15e6/o11nplugin-vro-core/src/main/java/com/vmware/avi/vro/AviVroClient.java#L634

**Comment by chaitanyaavi** [comment]
Fixed in https://github.com/avinetworks/avi-vrealize-orchestrator-plugin/pull/100
